[package]
name = "monoglu-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
js-sys = "0.3.59"
log = "0.4"
serde = { version = "1", features = ["derive"] }
wasm-bindgen = "0.2.82"
wasm-bindgen-futures = "0.4.32"
wasm-logger = "0.2"
web-sys = { version = "0.3.59", features = [
    "Blob",
    "BlobPropertyBag",
    "console",
    "DedicatedWorkerGlobalScope",
    "Document",
    "HtmlElement",
    "Location",
    "MessageEvent",
    "Node",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Storage",
    "Text",
    "Url",
    "Window",
    "Worker",
] }