[package]
name = "monoglu-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.1"
object_store = "0.5"
tokio = { version = "1", features = ["full"] }