[package]
name = "monoglu-webapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oauth2 = "4"
wasm-bindgen = "0.2"
web-sys = "0.3"
yew = "0.19"
yew-router = "0.16"